version: '3.8'

name: credit-system

services:
  # Nginx - веб-сервер
  nginx-credits:
    image: nginx:alpine
    container_name: credit-system-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/credit-system
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-credits
    networks:
      - credit-system-network

  # PHP с Symfony
  php-credits:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credit-system-php
    volumes:
      - ./:/var/www/credit-system
    environment:
      APP_ENV: dev
    networks:
      - credit-system-network

networks:
  credit-system-network:
    name: credit-system-network
    driver: bridge