version: '3.8'

name: credit-system-local

services:
  # Nginx - веб-сервер
  nginx-credits:
    image: nginx:alpine
    container_name: credit-system-nginx-local
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/credit-system
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-credits
    networks:
      - credit-system-network-local

  # PHP с Symfony
  php-credits:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credit-system-php-local
    volumes:
      - ./:/var/www/credit-system
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://app:password@db-credits:5432/credit_app?serverVersion=16&charset=utf8"
    depends_on:
      - db-credits
    networks:
      - credit-system-network-local

networks:
  credit-system-network-local:
    name: credit-system-network-local
    driver: bridge

volumes:
  credit-system-db-data-local:
    name: credit-system-db-data-local 