# Маршруты для контроллеров в инфраструктурном слое
infrastructure_controllers:
    resource:
        path: ../src/Infrastructure/Controller/
        namespace: App\Infrastructure\Controller
    type: attribute
